### ISSUE TITLE
多渠道智能客服系统，春松客服

### ISSUE THREAD

**Issue by Samurais** [JoneXiong/cs_base#1]
Odoo是基于Python的，目前已经闭源，对中小型企业不友好。
推荐使用基于Java的多渠道智能客服系统，春松客服。
https://github.com/chatopera/cosin

**Comment by JoneXiong** [comment]
1.  Odoo一直都是开源开放的
2. 系统好坏和使用的语言无关, Python也是目前热门语言
3. 这不是提bug的姿势
